version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dang-project-react-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules

  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dang-project-react-prod
    ports:
      - "8080:80"